name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy Development
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0
        with:
          channel: master
      - run: flutter packages get
      - run: flutter build web --web-renderer html --dart-define SHARING_ENABLED=true
      - uses: FirebaseExtended/action-hosting-deploy
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: photobooth-tm-30-a3631
          expires: 30d
          channelId: live
